### ISSUE TITLE
Puppeteer Support

### ISSUE THREAD

**Issue by puneet0191** [Percona-Lab/codeceptjs-resemblehelper#11]
Use the same logic with puppeteer driver

**Comment by rathovarun** [comment]
#19

**Comment by rathovarun** [comment]
#19 Update index.js
`

**Comment by rathovarun** [comment]
#19

**Comment by puneet0191** [comment]
Thanks, Support added as part of https://github.com/Percona-Lab/codeceptjs-resemblehelper/pull/24 closing the issue now.
