### ISSUE TITLE
Minor Improvements

### ISSUE THREAD

**Issue by puneet0191** [Percona-Lab/codeceptjs-resemblehelper#12]
- add support for IgnoredBox, with updated documentation

- add a debug to print the path to file, for printing the URL of the Diff Image in the console.

**Comment by prasadgujar** [comment]
@puneet0191 are you working on this issue?
if not let me know I m interested in solving issues.

**Comment by puneet0191** [comment]
@prasadgujar sure go ahead and help me with the issues, let me know how it goes

**Comment by prasadgujar** [comment]
Already started working on this issue. @puneet0191

**Comment by manciukass** [comment]
Hi, guys maybe you have any status about this request? Or know a workaround for ignoredBoxes to work :)

**Comment by puneet0191** [comment]
@manciukass  IgnoredBoxes can be used by providing element locator so that the screenshot comparison happens only for that element and ignores the rest of the area on the image. 
have you tried using : 
`seeVisualDiffForElement`

**Comment by manciukass** [comment]
Yes, I know that, but imagine a page with lots of elements, and let's say i would like to ignore half of the page from the bottom. I would not like to check every element separately. So idea to have possibility to check only some parts (big) of page would be really nice to have :)

**Comment by puneet0191** [comment]
@manciukass hmm you make sense, let me try to add this request as part of the new release which will be `1.6.0` coming out in some days

**Comment by manciukass** [comment]
That would be wonderful :)
