### ISSUE TITLE
Add support for Cloud Storage 

### ISSUE THREAD

**Issue by puneet0191** [Percona-Lab/codeceptjs-resemblehelper#3]
Need a function that can download base images from a cloud platform like Google -Drive, it should be parameterized, with the user, key and folder name as three input parameters. 

Base images can be downloaded on the fly from the cloud platform, preventing the need to store images on Github Repo. 

Similarly, Diff images generated can be uploaded on the cloud platform and link returned to the users.

**Comment by prasadgujar** [comment]
@puneet0191  what are the other cloud-based platform should be added? for example Microsoft-OneDrive.

**Comment by puneet0191** [comment]
Implemented, AWS support https://github.com/Percona-Lab/codeceptjs-resemblehelper/pull/28
