### ISSUE TITLE
browser.element is not a function

### ISSUE THREAD

**Issue by vitaly87** [Percona-Lab/codeceptjs-resemblehelper#30]
when I updated to last WebdriverIO 5 my tests are failing

`  browser.element is not a function
  
  Scenario Steps:
  
  - I.seeVisualDiffForElement(".infaOnglet", "Home_Page_Image.png", {"prepareBaseImage":false,"tolerance":1}) at Test.I (tests\visual-testing\homePage.js:27:7)
  - I.saveScreenshot("Home_Page_Image.png") at Test.I (tests\visual-testing\homePage.js:23:7)
  
  
  `

**Comment by puneet0191** [comment]
Known Issue with Windows, Please read about canvas node package issue with windows
