### ISSUE TITLE
Config: Why do we need screenshotFolder?

### ISSUE THREAD

**Issue by pablopaul** [Percona-Lab/codeceptjs-resemblehelper#36]
https://codecept.io/visual says

> screenshotFolder : This will always have the same value as output in Codecept configuration

Why do we need it then as config here? Instead the plugin could pull it directly from the CodeceptJS config, what do you think?

Smaller config surface, better plugin I would say :)

**Comment by puneet0191** [comment]
this is fixed, will be release as part of the new version. thanks for your suggestion.
