### ISSUE TITLE
Node crash if dimension mismatch in `I.seeVisualDiff`

### ISSUE THREAD

**Issue by tairun** [Percona-Lab/codeceptjs-resemblehelper#41]
- codeceptjs-resemblehelper: 1.6.0
- codeceptjs: 2.1.5
- node: 10.14.0

When using release 1.6.0 of this helper, node crashes with the following error if the dimension of the screenshots is not the same:

![error](https://user-images.githubusercontent.com/4248906/63012952-6e31cd80-be8b-11e9-9530-9289122d57ec.png)

This is most likely due to the version of resemblejs being used. In the package.json the version specified is: **^3.0.0** which installs **3.2.0**. A simple fix would be to always use *3.0.0*, which worked for me.

**Comment by Kartikeya99** [comment]
That error is set by choice. Because if the dimensions aren't same then the tool behaves a bit unpredictably.

**Comment by tairun** [comment]
> That error is set by choice. Because if the dimensions aren't same then the tool behaves a bit unpredictably.

I get that the diff-image produced by resemblejs with two images of different size isn't meaningful. But **NODE** crashes completely... which isn't a good thing. The error thrown should just cause the scenario to fail and then codeceptjs should get on with the next scenario. You still have the error in your tests about size mismatch in the end.

**Comment by tairun** [comment]
Instead of throwing error [here](https://github.com/Percona-Lab/codeceptjs-resemblehelper/blob/c043b88b2281a280450983f010a2148ab74a460d/index.js#L43), also `reject(throw new Error(...))` with error... then it will also work with version **3.2.0** of *resemblejs*.

**Comment by Kartikeya99** [comment]
Which node version are you using?

**Comment by tairun** [comment]
To quote myself here:

>     * codeceptjs-resemblehelper: 1.6.0
> 
>     * codeceptjs: 2.1.5
> 
>     * node: 10.14.0
>

**Comment by pablopaul** [comment]
I ran into the same today.
