### ISSUE TITLE
Suggestion to add width and height into "The images are not of same dimensions" error

### ISSUE THREAD

**Issue by FreshHead** [Percona-Lab/codeceptjs-resemblehelper#42]
Hello ✋ 
I have a proposal. I think error message that throws when images has different dimensions can be more informative. 
Right now message is: 
"The images are not of same dimensions. Please use images of same dimensions so as to avoid any unexpected results."
You can find it there https://github.com/Percona-Lab/codeceptjs-resemblehelper/blob/c043b88b2281a280450983f010a2148ab74a460d/index.js#L43
I am suggesting to add height and width there. Like: 
"The images are not of same dimensions. Image 1 is 1920x1080 and image 2 is 1920x1017. Please use images of same dimensions so as to avoid any unexpected results."

**Comment by puneet0191** [comment]
Thanks for suggestion @FreshHead  I really appreciate, I will have this updated.

**Comment by puneet0191** [comment]
@Kartikeya99 this one as well, please?

**Comment by puneet0191** [comment]
Fixed, will be available in the next version thanks
