### ISSUE TITLE
BaseFolder is not found when running codecept from outside test root folder

### ISSUE THREAD

**Issue by ashiots2** [Percona-Lab/codeceptjs-resemblehelper#50]
Relative path is not resolved in the helper.

Fixed it so that it will be resolved if baseFolder and diffFolder are not absolute paths.

Fixed in PR: https://github.com/Percona-Lab/codeceptjs-resemblehelper/pull/51

Looking forward to your review!

**Comment by puneet0191** [comment]
Fixed
