### ISSUE TITLE
Allure report does not show diff screenshot

### ISSUE THREAD

**Issue by ashiots2** [Percona-Lab/codeceptjs-resemblehelper#52]
Allure report shows the diff screenshot as corrupted; since the fs.writeFile() call is not finished when allure.addAttachment is called.

I replaced the fs.writeFile() call with fs.writeFileSync() in https://github.com/Percona-Lab/codeceptjs-resemblehelper/pull/51

Also covered some warnings the IDE highlighted.

Again, looking forward to your review :)

**Comment by puneet0191** [comment]
Fixed thanks
